spring:
  profiles:
    include: oauth # application-oauth.yml 파일 포함하겠다는 뜻
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${{ secrets.OAUTH_CLIENT_ID }}
            client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
            scope:
              - email
              - profile

jwt:
  issuer: bababaenjooo@gmail.com
  secret_key: study-springboot